# fly.toml app configuration file generated for ryckandmorty021 on 2023-10-27T10:00:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ryckandmorty021"
primary_region = "eze"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

